---
name: backend
on:
  workflow_run:
    workflows: [website]
    types:
      - completed
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/download-artifact@v4
        with:
          name: website-dist
      - run: unzip website-dist.zip -d dist
      - run: docker build . -t kiesel-in-stock-finder:latest
