---
name: ci
on:
  push:
    branches:
      - mainline
jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: ./website
      - run: npm run build
        working-directory: ./website
      - uses: actions/upload-artifact@v4
        with:
          name: website-dist
          path: website/dist

  build-backend:
    runs-on: ubuntu-latest
    needs: [build-website]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/download-artifact@v4
        with:
          name: website-dist
          path: backend/dist
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker buildx create --use
      - run: docker buildx build . -t ajchili/kiesel-in-stock-finder:latest --platform linux/amd64,linux/arm64 --push
        working-directory: ./backend
