---
name: ci
on:
  push:
    branches:
      - mainline
jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: ./website
      - run: npm run build
        working-directory: ./website
      - uses: actions/upload-artifact@v4
        with:
          name: website-dist
          path: website/dist

  build-backend:
    runs-on: ubuntu-latest
    needs: [build-website]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/download-artifact@v4
        with:
          name: website-dist
          path: backend/dist
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: commit-hash
        run: echo "COMMIT_HASH=$(git rev-parse --short=8 HEAD)" >> "$GITHUB_OUTPUT"
      - run: docker build . -t ajchili/kiesel-in-stock-finder:latest -t ajchili/kiesel-in-stock-finder:${{ steps.commit-hash.outputs.COMMIT_HASH }}
        working-directory: ./backend
      - run: docker push ajchili/kiesel-in-stock-finder

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend]
    defaults:
      run:
        working-directory: ./packages/infrastructure
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ajchili/kiesel-in-stock-finder/prod
          work-dir: ./packages/infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
