---
name: website
on:
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: ./website
      - run: npm run build
        working-directory: ./website
      - uses: actions/upload-artifact@v4
        with:
          name: website-dist
          path: website/dist
